### ISSUE TITLE
Implement basic new repo hygiene

### ISSUE THREAD

**Issue by vibhatha** [substrait-io/substrait-python#2]
This repository is in a very early stage of development. Once the first PR is merged we should probably work on the following

- [x] #3
- [ ] Adding Integration tests (evaluate)
- [x] #4
  - [x] Protect main branch

**Comment by westonpace** [comment]
I've configured this repo similar to the other repos:

 * The commit message defaults to PR title + description
 * Only squash-merge of PRs is enabled (e.g. no rebase merge or unsquashed merge)
 * `main` is protected (force push disabled), can only be updated via PR, PRs require 1 approval, linear history enforced

Let me know if you want any other configuration

**Comment by gforsyth** [comment]
I'm going to close this out -- `ibis-substrait` is using this library as the upstream provider of the substrait protobuf definitions and it's working well.  There's still lots to do, I'm sure, but I think we're good on the basic hygiene aspects.
