### ISSUE TITLE
Adding CIs

### ISSUE THREAD

**Issue by vibhatha** [substrait-io/substrait-python#3]
After the initial PR, we should probably add CIs.

**Comment by westonpace** [comment]
> Do you think https://github.com/substrait-io/substrait-python/pull/5 is enough to close this issue?

Yes

**Comment by westonpace** [comment]
Though maybe lets make a follow-up issue for linters / formatters (which are not part of #5 if I understand)

**Comment by danepitkin** [comment]
Added #6!
